theme = "base16_new"

[editor]
true-color = true
line-number = "relative"
mouse = true
color-modes = true
bufferline = "multiple"
auto-format = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
center = ["version-control", "separator", "file-type"]
separator = " |"

[editor.auto-save]
focus-lost = true

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"C-]" = "jump_view_right"
"C-[" = "jump_view_left"
Cmd-s = ":write"
C-r = ":config-reload"
"Cmd-c" = ":clipboard-yank"
"Cmd-v" = ":clipboard-paste-before"
C-k = "@X\"1dk\"1P;"
C-j = "@X\"1dj\"1P;"

[keys.select]
C-j = "@X\"1dj\"1P"
C-k = "@X\"1dk\"1P"
Cmd-c = ":clipboard-yank"

[keys.insert]
"C-v" = ":clipboard-paste-before"
A-left = "move_prev_word_end"
A-right = "move_next_word_start"
Cmd-left = "goto_line_start"
Cmd-right = "goto_line_end"


[keys.insert.j]
j = "normal_mode"

[keys.normal.space.g]
f = "changed_file_picker"
r = ":reset-diff-change"
# inline blame
b = ":run-shell-command ~/.config/helix/utils/blame_line_pretty.sh %{buffer_name} %{cursor_line}"
# full last commit in the line changes for the file
B = ':open %sh{~/.config/helix/utils/blame_file_pretty.sh %{buffer_name} %{cursor_line}}'
# inline hunk changes
h = ':run-shell-command ~/.config/helix/utils/git-hunk.sh %{buffer_name} %{cursor_line} 3' 
